"""add goals and plans tables

Revision ID: c47bdc51b3a2
Revises: e7b3ce05e870
Create Date: 2026-06-16 17:16:47.548716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c47bdc51b3a2'
down_revision: Union[str, Sequence[str], None] = 'e7b3ce05e870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('linked_todo_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_user_id'), 'goal', ['user_id'], unique=False)
    op.create_table('plan',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('end_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_user_id'), 'plan', ['user_id'], unique=False)
    op.drop_index(op.f('ix_reminder_user_id'), table_name='reminder')
    op.drop_table('reminder')
    op.drop_constraint(op.f('uq_userprofile_user_id'), 'userprofile', type_='unique')
    op.drop_index(op.f('ix_userprofile_user_id'), table_name='userprofile')
    op.create_index(op.f('ix_userprofile_user_id'), 'userprofile', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userprofile_user_id'), table_name='userprofile')
    op.create_index(op.f('ix_userprofile_user_id'), 'userprofile', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('uq_userprofile_user_id'), 'userprofile', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_table('reminder',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('due_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('reminder_pkey'))
    )
    op.create_index(op.f('ix_reminder_user_id'), 'reminder', ['user_id'], unique=False)
    op.drop_index(op.f('ix_plan_user_id'), table_name='plan')
    op.drop_table('plan')
    op.drop_index(op.f('ix_goal_user_id'), table_name='goal')
    op.drop_table('goal')
    # ### end Alembic commands ###
